# GitHub Pages configuration
title: "Joocode Panel Management"
description: "Modern responsive Pterodactyl panel management application"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - node_modules/
  - vendor/
  - .gitignore
  - .git/

# Include files
include:
  - _redirects

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# GitHub Pages safe plugins
safe: true
lsi: false
source: .
incremental: false
gist:
  noscript: false

# Collections
collections_dir: collections

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
